server:
  port: 8082

spring:
  application:
    name: inventoryService

  datasource:
    url: jdbc:postgresql://localhost:5433/products_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update   # create | update | validate | none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

grpc:
  port: 9090
