server:
  port: 8082

spring:
  application:
    name: inventoryService

  datasource:
    url: ${INVENTORY_SERVICE_DATASOURCE_URL}
    username: ${INVENTORY_SERVICE_DATASOURCE_USERNAME}
    password: ${INVENTORY_SERVICE_DATASOURCE_PASSWORD}
    driverClassName: ${INVENTORY_SERVICE_DATASOURCE_DRIVER}


  jpa:
    hibernate:
      ddl-auto: update   # create | update | validate | none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

grpc:
  port: 9090
