[versions]
grpc-ver = "1.75.0"
grpc-stub = "1.63.0"
jjwt-ver = "0.12.5"

[libraries]

mapstruct = { module = "org.mapstruct:mapstruct", version = "1.5.5.Final" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor", version = "1.5.5.Final" }

jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version = "2.13.4.2" }


jwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt-ver" }
jwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt-ver" }
jwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt-ver" }
annotation-api = { module = "javax.annotation:javax.annotation-api", version = "1.3.2" }

lombok = { module = "org.projectlombok:lombok" }

grpc-transport = { module = "io.grpc:grpc-netty-shaded", version.ref = "grpc-ver" }
grpc-model = { module = "io.grpc:grpc-protobuf", version.ref = "grpc-ver" }
grpc-stub = { module = "io.grpc:grpc-stub", version.ref = "grpc-stub" }
spring-boot-grpc-client = { module = "net.devh:grpc-client-spring-boot-starter", version = "3.1.0.RELEASE" }

grpc-spring-boot-starter = { module = "io.github.lognet:grpc-spring-boot-starter", version = "5.1.5" }

spring-boot-starter = { module = "org.springframework.boot:spring-boot-starter" }
spring-security-test = { module = "org.springframework.security:spring-security-test" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-test-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-starter-kafka = { module = "org.springframework.boot:spring-boot-starter-kafka", version = "4.0.0" }

postgresql = { module = "org.postgresql:postgresql", version = "42.7.3" }

junit-bom = { module = "org.junit:junit-bom", version = "5.10.0" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }


[plugins]
java-plugin = { id = "java" }
protobuf-plugin = { id = "com.google.protobuf", version = "0.9.4" }
spring-boot-plugin = { id = "org.springframework.boot", version = "4.0.0" }
spring-dependency-plugin = { id = "io.spring.dependency-management", version = "1.1.7" }