server:
  port: 8083

spring:
  application:
    name: notificationService

  datasource:
    url: ${NOTIFICATION_SERVICE_DATASOURCE_URL}
    username: ${NOTIFICATION_SERVICE_DATASOURCE_USERNAME}
    password: ${NOTIFICATION_SERVICE_DATASOURCE_PASSWORD}
    driverClassName: ${NOTIFICATION_SERVICE_DATASOURCE_DRIVER}

  jpa:
    hibernate:
      ddl-auto: update   # create | update | validate | none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect